services:
  # postgres:
  #   image: postgres:13
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   # networks:
  #   #   - mynetwork

  # pgadmin:
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - postgres
    # networks:
    #   - mynetwork
      
#   nestjs:
#       build: .
#       command: npm run start:dev
#       volumes:
#         - .:/app
#         - /app/node_modules
#       environment:
#         - POSTGRES_HOST=postgres
#         - POSTGRES_USER=${POSTGRES_USER}
#         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#         - POSTGRES_DB=${POSTGRES_DB}
#       ports:
#         - 3001:3001
#       depends_on:
#         - postgres
#       networks:
#         - mynetwork

# networks:
#   mynetwork:
#     driver: bridge

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=w3bDB
      - MYSQL_ROOT_PASSWORD=w3admin
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=w3admin
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql